// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TL.Data;

#nullable disable

namespace TL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515000000_AddMissedTargetReasons")]
    partial class AddMissedTargetReasons
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
