// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TL.Data;

#nullable disable

namespace TL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TL.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TL.Models.MissedTargetReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasDefaultValue(true)
                        .HasColumnType("bit");

                    b.Property<string>("ReasonText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MissedTargetReasons");
                });

            modelBuilder.Entity("TL.Models.HourlyCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AccidentsReported")
                        .HasColumnType("bit");

                    b.Property<bool?>("DeviationsEscalated")
                        .HasColumnType("bit");

                    b.Property<bool?>("EscalationsNeeded")
                        .HasColumnType("bit");

                    b.Property<bool?>("HazardsObserved")
                        .HasColumnType("bit");

                    b.Property<byte>("HourNumber")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("HourlyTargetAchieved")
                        .HasColumnType("bit");

                    b.Property<bool?>("MaintenanceIssues")
                        .HasColumnType("bit");

                    b.Property<bool?>("MaterialsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("MissedTargetNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MissedTargetReasonId")
                        .HasColumnType("int");

                    b.Property<string>("MoraleNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("NCPartsStoredCorrectly")
                        .HasColumnType("bit");

                    b.Property<bool?>("NonComplianceAddressed")
                        .HasColumnType("bit");

                    b.Property<string>("OverallPerfStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallQualityStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallSafetyStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PartsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool?>("PartsIdCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("PerformanceNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PositiveBehaviours")
                        .HasColumnType("bit");

                    b.Property<bool?>("QualityChecksCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("QualityNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SafetyNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShiftSubmissionId")
                        .HasColumnType("int");

                    b.Property<bool?>("SixSCompleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("SupportRequired")
                        .HasColumnType("bit");

                    b.Property<bool?>("TPMCompleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("ToolsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool?>("UnsafeBehaviours")
                        .HasColumnType("bit");

                    b.Property<bool?>("WellbeingConfirmed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ShiftSubmissionId");

                    b.ToTable("HourlyChecks");
                });

            modelBuilder.Entity("TL.Models.ShiftSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Escalations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("HoursCompleted")
                        .HasColumnType("tinyint");

                    b.Property<string>("IncomingTLSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyRisks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastEditedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastEditedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutgoingTLSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priorities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamLeaderDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShiftSubmissions");
                });

            modelBuilder.Entity("TL.Models.AuditLog", b =>
                {
                    b.HasOne("TL.Models.ShiftSubmission", "Submission")
                        .WithMany("AuditLogs")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("TL.Models.HourlyCheck", b =>
                {
                    b.HasOne("TL.Models.ShiftSubmission", null)
                        .WithMany("Hours")
                        .HasForeignKey("ShiftSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TL.Models.ShiftSubmission", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Hours");
                });
#pragma warning restore 612, 618
        }
    }
}
