// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TL.Data;

#nullable disable

namespace TL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TL.Models.AuditSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionOwner").HasColumnType("nvarchar(max)");
                    b.Property<DateOnly?>("ActionDueDate").HasColumnType("date");
                    b.Property<string>("ActionsRaised").HasColumnType("nvarchar(max)");
                    b.Property<bool?>("AccidentsObserved").HasColumnType("bit");
                    b.Property<string>("Area").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("AuditorName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("AuditorSignature").HasColumnType("nvarchar(max)");
                    b.Property<DateOnly>("AuditDate").HasColumnType("date");
                    b.Property<bool?>("DeviationsEscalated").HasColumnType("bit");
                    b.Property<bool?>("EscalationsNeeded").HasColumnType("bit");
                    b.Property<string>("FollowUpRequired").HasColumnType("nvarchar(max)");
                    b.Property<string>("GoodPracticeObserved").HasColumnType("nvarchar(max)");
                    b.Property<bool?>("HazardsObserved").HasColumnType("bit");
                    b.Property<bool?>("HourlyTargetAchieved").HasColumnType("bit");
                    b.Property<string>("LastEditedBy").HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("LastEditedAt").HasColumnType("datetime2");
                    b.Property<bool?>("MaintenanceIssues").HasColumnType("bit");
                    b.Property<bool?>("MaterialsAvailable").HasColumnType("bit");
                    b.Property<string>("MoraleNotes").HasColumnType("nvarchar(max)");
                    b.Property<bool?>("NCPartsStoredCorrectly").HasColumnType("bit");
                    b.Property<bool?>("NonComplianceAddressed").HasColumnType("bit");
                    b.Property<string>("OverallPerfStatus").HasColumnType("nvarchar(max)");
                    b.Property<string>("OverallQualityStatus").HasColumnType("nvarchar(max)");
                    b.Property<string>("OverallSafetyStatus").HasColumnType("nvarchar(max)");
                    b.Property<bool?>("PartsConfirmed").HasColumnType("bit");
                    b.Property<bool?>("PartsIdCorrect").HasColumnType("bit");
                    b.Property<string>("PerformanceNotes").HasColumnType("nvarchar(max)");
                    b.Property<bool?>("PositiveBehavioursPraised").HasColumnType("bit");
                    b.Property<string>("QualityNotes").HasColumnType("nvarchar(max)");
                    b.Property<bool?>("QualityChecksCompleted").HasColumnType("bit");
                    b.Property<string>("SafetyNotes").HasColumnType("nvarchar(max)");
                    b.Property<string>("ShiftObserved").HasColumnType("nvarchar(max)");
                    b.Property<bool?>("SixSCompleted").HasColumnType("bit");
                    b.Property<string>("SubmittedBy").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("SubmittedAt").HasColumnType("datetime2");
                    b.Property<bool?>("SupportRequired").HasColumnType("bit");
                    b.Property<string>("TLOnShift").HasColumnType("nvarchar(max)");
                    b.Property<bool?>("TPMCompleted").HasColumnType("bit");
                    b.Property<bool?>("ToolsAvailable").HasColumnType("bit");
                    b.Property<bool?>("UnsafeBehavioursObserved").HasColumnType("bit");
                    b.Property<bool?>("WellbeingConfirmed").HasColumnType("bit");

                    b.HasKey("Id");
                    b.ToTable("AuditSubmissions");
                });

            modelBuilder.Entity("TL.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TL.Models.HourlyCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AccidentsReported")
                        .HasColumnType("bit");

                    b.Property<bool?>("DeviationsEscalated")
                        .HasColumnType("bit");

                    b.Property<bool?>("EscalationsNeeded")
                        .HasColumnType("bit");

                    b.Property<bool?>("HazardsObserved")
                        .HasColumnType("bit");

                    b.Property<byte>("HourNumber")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("HourlyTargetAchieved")
                        .HasColumnType("bit");

                    b.Property<bool?>("MaintenanceIssues")
                        .HasColumnType("bit");

                    b.Property<bool?>("MaterialsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("MoraleNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("NCPartsStoredCorrectly")
                        .HasColumnType("bit");

                    b.Property<bool?>("NonComplianceAddressed")
                        .HasColumnType("bit");

                    b.Property<bool?>("ToolsMatchInspectionPlan")
                        .HasColumnType("bit");

                    b.Property<string>("OverallPerfStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallQualityStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallSafetyStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PartsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool?>("PartsIdCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("PerformanceNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PositiveBehaviours")
                        .HasColumnType("bit");

                    b.Property<bool?>("QualityChecksCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("QualityNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SafetyNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShiftSubmissionId")
                        .HasColumnType("int");

                    b.Property<bool?>("SixSCompleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("SupportRequired")
                        .HasColumnType("bit");

                    b.Property<bool?>("TPMCompleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("ToolsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool?>("UnsafeBehaviours")
                        .HasColumnType("bit");

                    b.Property<bool?>("WellbeingConfirmed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ShiftSubmissionId");

                    b.ToTable("HourlyChecks");
                });

            modelBuilder.Entity("TL.Models.ShiftSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoveringFor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Escalations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("HoursCompleted")
                        .HasColumnType("tinyint");

                    b.Property<string>("IncomingTLSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IncomingTLSignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("KeyRisks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastEditedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastEditedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutgoingTLSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priorities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamLeaderDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShiftSubmissions");
                });

            modelBuilder.Entity("TL.Models.AuditLog", b =>
                {
                    b.HasOne("TL.Models.ShiftSubmission", "Submission")
                        .WithMany("AuditLogs")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("TL.Models.HourlyCheck", b =>
                {
                    b.HasOne("TL.Models.ShiftSubmission", null)
                        .WithMany("Hours")
                        .HasForeignKey("ShiftSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TL.Models.ShiftSubmission", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Hours");
                });

            modelBuilder.Entity("TL.Models.SeniorWeeklyAudit", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("AuditorName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateOnly>("AuditDate").HasColumnType("date");
                    b.Property<string>("Area").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("SubmittedBy").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("SubmittedAt").HasColumnType("datetime2");
                    b.Property<byte?>("HandoverStandardsFollowed").HasColumnType("tinyint");
                    b.Property<byte?>("VisualManagementCurrent").HasColumnType("tinyint");
                    b.Property<byte?>("EscalationPathsUsed").HasColumnType("tinyint");
                    b.Property<string>("GovernanceNotes").HasColumnType("nvarchar(max)");
                    b.Property<byte?>("PpeComplianceFull").HasColumnType("tinyint");
                    b.Property<byte?>("NearMissesReported").HasColumnType("tinyint");
                    b.Property<byte?>("SafetyActionLogCurrent").HasColumnType("tinyint");
                    b.Property<string>("SafetyNotes").HasColumnType("nvarchar(max)");
                    b.Property<byte?>("FirstOffRecordsComplete").HasColumnType("tinyint");
                    b.Property<byte?>("NcCaptureTrended").HasColumnType("tinyint");
                    b.Property<byte?>("NcProcedureFollowed").HasColumnType("tinyint");
                    b.Property<byte?>("QualityGatesMaintained").HasColumnType("tinyint");
                    b.Property<string>("QualityNotes").HasColumnType("nvarchar(max)");
                    b.Property<byte?>("LeaderVisibilityCheck").HasColumnType("tinyint");
                    b.Property<string>("LastTeamMeeting").HasColumnType("nvarchar(max)");
                    b.Property<byte?>("AbsenceManagedProactively").HasColumnType("tinyint");
                    b.Property<byte?>("TlsCoachingTeams").HasColumnType("tinyint");
                    b.Property<byte?>("TrainingMatrixCurrent").HasColumnType("tinyint");
                    b.Property<string>("PeopleNotes").HasColumnType("nvarchar(max)");
                    b.Property<byte?>("SixSStandardMaintained").HasColumnType("tinyint");
                    b.Property<byte?>("TpmScheduleFollowed").HasColumnType("tinyint");
                    b.Property<byte?>("StandardWorkVisible").HasColumnType("tinyint");
                    b.Property<byte?>("StandardWorkMaintained").HasColumnType("tinyint");
                    b.Property<string>("StandardsNotes").HasColumnType("nvarchar(max)");
                    b.Property<byte?>("TrackingAgainstWeeklyPlan").HasColumnType("tinyint");
                    b.Property<byte?>("MetricsVisibleAndOwned").HasColumnType("tinyint");
                    b.Property<byte?>("ImprovementActionsProgressing").HasColumnType("tinyint");
                    b.Property<string>("PerformanceNotes").HasColumnType("nvarchar(max)");
                    b.Property<string>("GoodPracticeObserved").HasColumnType("nvarchar(max)");
                    b.Property<string>("AreasForImprovement").HasColumnType("nvarchar(max)");
                    b.Property<string>("ActionsRaised").HasColumnType("nvarchar(max)");
                    b.Property<string>("OverallVerdict").HasColumnType("nvarchar(max)");
                    b.Property<string>("AuditorSignature").HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("SeniorWeeklyAudits");
                });

            modelBuilder.Entity("TL.Models.HodDailyAudit", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("ActionsRaised").HasColumnType("nvarchar(max)");
                    b.Property<DateOnly>("AuditDate").HasColumnType("date");
                    b.Property<string>("AuditType").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("AnswersJson").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Area").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("AuditorName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("AuditorSignature").HasColumnType("nvarchar(max)");
                    b.Property<string>("Department").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("EffectivenessArea").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("EffectivenessJson").HasColumnType("nvarchar(max)");
                    b.Property<string>("GoodPractice").HasColumnType("nvarchar(max)");
                    b.Property<string>("LastEditedBy").HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("LastEditedAt").HasColumnType("datetime2");
                    b.Property<int>("MaxScore").HasColumnType("int");
                    b.Property<DateTime>("SubmittedAt").HasColumnType("datetime2");
                    b.Property<string>("SubmittedBy").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("TeamLeaderSignature").HasColumnType("nvarchar(max)");
                    b.Property<int>("TotalScore").HasColumnType("int");
                    b.HasKey("Id");
                    b.ToTable("HodDailyAudits");
                });

            modelBuilder.Entity("TL.Models.PickerPerson", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("ListKind").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<int>("SortOrder").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("ListKind", "Name").IsUnique();
                    b.ToTable("PickerPersons");
                });
#pragma warning restore 612, 618
        }
    }
}
