namespace TL.Models;

public static class AreaList
{
    public static readonly (string Group, string Label)[] All =
    [
        ("Assembly", "1 — HP"),
        ("Assembly", "2 — OZEKI"),
        ("Assembly", "3 — META"),
        ("Assembly", "4 — SELL"),
        ("Assembly", "5 — MICROSOFT"),
        ("Assembly", "6 — DELL GAINS / RAINWATER"),
        ("Assembly", "7 — MOR"),
        ("Assembly", "8 — SPECIALS"),
        ("Assembly", "9 — TX"),
        ("Assembly", "10 — E40001"),
        ("Assembly", "11 — FLAT PARTS"),
        ("Assembly", "12 — ACCESSORIES"),
        ("Paint", "13 — Black Line"),
        ("Paint", "14 — White Line"),
        ("Paint", "15 — Back Booth"),
        ("Paint", "16 — Re-Work"),
        ("Sheet Metal", "17 — Trumpf Laser"),
        ("Sheet Metal", "18 — T500"),
        ("Sheet Metal", "19 — T5000"),
        ("Sheet Metal", "20 — T5000 - S10"),
        ("Sheet Metal", "21 — T5000 - S11"),
        ("Sheet Metal", "22 — T5000 - S13"),
        ("Sheet Metal", "23 — T5000 - S14"),
        ("Sheet Metal", "24 — T7000"),
        ("Sheet Metal", "25 — Heilbronn"),
        ("Sheet Metal", "26 — Salvi 1"),
        ("Sheet Metal", "27 — Salvi 3"),
        ("Sheet Metal", "28 — Horizontal Roll Form"),
        ("Sheet Metal", "29 — Vertical Roll Form"),
        ("Sheet Metal", "30 — Mainframe 1"),
        ("Sheet Metal", "31 — Mainframe 2"),
        ("Sheet Metal", "32 — Microsoft"),
        ("Sheet Metal", "33 — HP Weld"),
        ("Sheet Metal", "34 — German Jig 1 (SPC)"),
        ("Sheet Metal", "35 — German Jig 1 (Dell)"),
        ("Sheet Metal", "36 — Panasonic (V3 & Nvidia)"),
        ("Sheet Metal", "37 — MGX Galv Weld"),
        ("Sheet Metal", "38 — Google Small Part Galve Weld"),
        ("Sheet Metal", "39 — Microsoft Tops and Bottoms"),
        ("Sheet Metal", "40 — R22 Weld Robot"),
        ("Sheet Metal", "41 — Small Parts Welding"),
        ("Sheet Metal", "42 — 160T Xact"),
        ("Sheet Metal", "43 — 100T Procam"),
        ("Sheet Metal", "44 — PH1 ED PRSN"),
        ("Sheet Metal", "45 — Training Bay"),
        ("Sheet Metal", "46 — PH3 ED PRSN"),
        ("Sheet Metal", "47 — 250T"),
        ("Sheet Metal", "48 — Robot Folding Cell 200T"),
        ("Sheet Metal", "49 — Bystronic 200T"),
        ("Sheet Metal", "50 — Bystronic 200T Machine 3"),
        ("Sheet Metal", "51 — Bystronic 200T 4 Robot"),
        ("Sheet Metal", "52 — Trubend F32"),
        ("Sheet Metal", "53 — Trubend F33"),
        ("Sheet Metal", "54 — Trubend F34"),
        ("Sheet Metal", "55 — Trubend F35"),
        ("Sheet Metal", "56 — Grind Master PH1"),
        ("Sheet Metal", "57 — PH1 Grind"),
        ("Sheet Metal", "58 — Automatic TX Stud Weld Cell"),
        ("Sheet Metal", "59 — Rels RL16 Stud Welder"),
        ("Sheet Metal", "60 — EL Grind"),
    ];
}
